### ISSUE TITLE
Общее: Сделать поиск экстендером к сниппету.

### ISSUE THREAD

**Issue by deversjkee** [DivanDesign/MODXEvo.snippet.ddGetDocuments#4]
Сделать поиск экстендером к сниппету.
Доработаный поиск есть на сайте запчастиесть.рф. Надо его взять и встроить в сниппет ddGetDocuments как экстендер.

**Comment by Ronef** [comment]
766cb27e73798ae2f4126e9b8669c44de5060c4e
